ruby:
- any: ['./**/*.rb ']

javascript: 
- any: ['./**/*.js', './**/*.ts*']

spec:
- any: ['spec/**', './**/*.spec.js', './**/*.spec.ts*']

model:
- any: ['app/models/**']

controller:
- any: ['app/controllers/**']

mailer:
- any: ['app/mailers/**']

view:
- any: ['app/views/**']

job:
- any: ['app/jobs/**']

dependencies: 
- any: ['Gemfile.lock', 'yarn.lock', 'gems/**']

config:
- any: ['./config/**']

widget: 
- any: ['app/javascript/donate-button/*', 'app/assets/stylesheets/donate-button/*']
